name = "spearyx-jobs-cron"
main = "src/cron-worker.ts"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"] # Run every 5 minutes

[observability]
enabled = true
